### ISSUE TITLE
Thoughts on a Core XY Version?

### ISSUE THREAD

**Issue by NullVoxPopuli** [eclsnowman/Eustathios-Spider-V2#3]
corexy seems to be the best way of moving the x/y axis. Are there plans to modify this design to work with that?

**Comment by justinledwards** [comment]
Best in what way?

**Comment by NullVoxPopuli** [comment]
equal tension in all x/y directions -- which allows for faster, more accurate prints

**Comment by justinledwards** [comment]
It's less constrained and relies on more things to have tighter tolerances and usually doesn't incorporate any preloading, which makes it print less well, and has to run slower to get good results.  

The proof is in the end product.

**Comment by eclsnowman** [comment]
Nope. I guess I disagree corexy is best. Mostly because I designed and ran
one before. Infact Herculien is based on the frame of my old corexy. I
moved to this ingentis/ultimaker style gantry design. I am much happier
than I was with corexy, and it has required no maintenance in almost 2
years so it is more repeatable than my corexy ever was.
